
= Environmental Data Collection and Visualisation using Arduino Cloud IoT with Sensors

The main code for the project is titled as Temperature_and_Humidity_Monitoring_a

This code executes the collection of environmental data using sensors connected to a Microcontroller Unit to process the data to the Arduino IoT Cloud which can be used to monitor and control the system designed. Using a range of sensors connected to the IoT module ESP 8266, the devices circuitry involves LEDs which can implement a temperature control logic. A mobile app is used with widgets dashboard to display the temperature, humidity, fan, and heating data on the Arduino cloud which can be accessible anywhere by the user. Also, a smart alarm system has been connected to automatically set the temperature to a preferred level throughout the day. 


=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
